---
##BETA VERSION
# used by the capabilities generation
legend_root_url: "http://wyvis.edina.ac.uk/legend_icons"
clive_root_urql: "http://dm-services-kb.edina.ac.uk:8992/clive/clive?"

# Overriding property in common.yaml
cadcorp_wsdl_host: "http://lui.edina.ac.uk"
